source "https://rubygems.org"

gem "rails", "4.1.8"
gem "mysql2"
gem "sass-rails", "~> 4.0.3"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.0.0"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"

gem "devise"
gem "directiveadmin", github: "archan937/directiveadmin"
gem "country_select"
gem "pry"
